# Generated by Django 4.0.6 on 2022-07-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
    ]
