# Generated by Django 4.0.6 on 2022-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_remove_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
