# Generated by Django 4.0.6 on 2022-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_url_active_url_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
