# Generated by Django 4.0.6 on 2022-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_alter_url_long_url_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
