# Generated by Django 4.0.6 on 2022-07-21 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('url', '0006_alter_url_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField()),
                ('os', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ManyToManyField(related_name='urls', through='url.Info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='info',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkinfo', to='url.url'),
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urlinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
