# Generated by Django 4.0.6 on 2022-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0007_info_remove_url_created_at_url_user_info_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='os',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='response_time',
            field=models.FloatField(null=True),
        ),
    ]
